package beercraft.ingredients;

import beercraft.MeasurementType;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.*;

@DynamoDBTable(tableName = "Extras")
public class Extra implements Ingredient {
    private String id;
    private String name;
    private String notes;
    private double defaultAmount;
    private double defaultTimeInMinutes;
    private IngredientUse defaultUse;
    private ExtraCategory category;
    private MeasurementType measurementType;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "Notes")
    public String getNotes() {
        return notes;
    }
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @DynamoDBAttribute(attributeName = "DefaultAmount")
    public double getDefaultAmount() {
        return defaultAmount;
    }
    public void setDefaultAmount(double defaultAmount) {
        this.defaultAmount = defaultAmount;
    }

    @DynamoDBAttribute(attributeName = "DefaultTimeInMinutes")
    public double getDefaultTimeInMinutes() {
        return defaultTimeInMinutes;
    }
    public void setDefaultTimeInMinutes(double defaultTimeInMinutes) { this.defaultTimeInMinutes = defaultTimeInMinutes; }

    @DynamoDBTyped(DynamoDBAttributeType.S)
    public IngredientUse getDefaultUse() { return defaultUse; }
    public void setDefaultUse(IngredientUse defaultUse) { this.defaultUse = defaultUse; }

    @DynamoDBTyped(DynamoDBAttributeType.S)
    public ExtraCategory getCategory() { return category; }
    public void setCategory(ExtraCategory category) { this.category = category; }

    @DynamoDBTyped(DynamoDBAttributeType.S)
    public MeasurementType getMeasurementType() { return measurementType; }
    public void setMeasurementType(MeasurementType measurementType) { this.measurementType = measurementType; }
}
